#!/usr/bin/env bash

AT_PLUGIN_NAME="esync"
AT_PLUGIN_INFO="Включить поддержку esync. Повышает производительность
многих игр, особенно тех, которые в значительной степени
зависят от многопоточности. (значение взято из SteamOS)"

at_plugin_check () {
    [ -e /etc/security/limits.d/99-esync.conf ] && return 0 || return 1
}

at_plugin_function () {
    cat << EOF >> /etc/security/limits.d/99-esync.conf
*		soft	nofile	1024
*		hard	nofile	524288
EOF
[ "$?" == 0 ] && return 0 || return 1
}

at_plugin_restore_to_default () {
    rm /etc/security/limits.d/99-esync.conf && return 0 || return 1
}
